version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc-server
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      - EULA=TRUE
      - MEMORY=2G
      - TYPE=PAPER
      - ENABLE_RCON=true
      - RCON_PASSWORD=your_secure_password
      - RCON_PORT=25575
    volumes:
      - ./data/minecraft:/data
    restart: unless-stopped
    tty: true
    stdin_open: true

  web-ui:
    image: node:16-alpine
    container_name: mc-web-ui
    working_dir: /app
    volumes:
      - ./data/web-ui:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    restart: unless-stopped
    depends_on:
      - minecraft
    environment:
      - MINECRAFT_HOST=minecraft
      - RCON_PASSWORD=your_secure_password

networks:
  default:
    name: minecraft-network
